<?xml version="1.0" encoding="utf-8"?><Database Name="LINQSample" Class="SampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-GNT05A0P;Initial Catalog=LINQSample;Persist Security Info=True;User ID=LINQTester" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LINQSampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Gamer" Member="Gamer">
    <Type Name="Gamer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>